# use Ubuntu 14.04
sudo: required
dist: trusty

language: cpp
before_install:
    - sudo apt-get update -qq
    # packages required by ROOT
    - sudo apt-get install -y git dpkg-dev make g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev gfortran libssl-dev libpcre3-dev xlibmesa-glu-dev libglew1.5-dev libftgl-dev libmysqlclient-dev libfftw3-dev cfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl0-dev libqt4-dev
    # packages required by ROOTPWA
    - sudo apt-get install -y libconfig++-dev libyaml-cpp-dev
    # fix Python library
    - sudo rm -f /opt/python/2.7.10/lib/python2.7/config/libpython2.7.a
    - sudo ln -sf /opt/python/2.7.10/lib/libpython2.7.so /opt/python/2.7.10/lib/python2.7/config/libpython2.7.so
    - ./travisCI/install-cmake.sh
    - export PATH=${PWD}/cmake/bin:${PATH}
    - ./travisCI/install-boost.sh 1.61.0
    - export BOOST_ROOT=${PWD}/boost-boost-1.61.0
    - ./travisCI/install-root.sh
    - . ./root/bin/thisroot.sh
    - export ROOTPWA=$PWD
install:
    - cd ${ROOTPWA}/build
    - cmake ..
    - make
before_script: echo "before_script nop"
script: echo "script nop"
cache: apt
notifications:
    email:
        recipients: rootpwa-push-notifications@lists.sourceforge.net
        on_success: change
        on_failure: always
